Neos:
  Imagine:
    driver: Gd
  Flow:
    persistence:
      backendOptions:
        driver: 'pdo_mysql'
        charset: 'utf8'
        host: '%env:DB_NEOS_HOST%'
        port: '%env:DB_NEOS_PORT%'
        password: '%env:DB_NEOS_PASSWORD%'
        user: '%env:DB_NEOS_USER%'
        dbname: '%env:DB_NEOS_DATABASE%'
  ContentRepository:
    Search:
    # API. If set to FALSE, only index the "live" workspace and not user workspaces.
    # If you only index the live workspace, Search will not work for your editors in the user workspaces.
    # Furthermore, if you heavily rely on Search for collecting content, this might be strange for editors to
    # work with -- as unpublished changes are not indexed right away.
    indexAllWorkspaces: false
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'mailhog'
        port: '1025'
Flowpack:
  ElasticSearch:
    clients:
      default:
        - host: elastic
          port: 9200
Ws:
  Fshsite:
    memberDatabase:
      driver: 'pdo_mysql'
      host: 'host.docker.internal'
      user: '%env:MEMBER_DB_USER%'
      password: '%env:MEMBER_DB_PASSWORD%'
      dbname: '%env:MEMBER_DB_DATABASE%'
